branch-defaults:
  master:
    environment: evermarkets
deploy:
  artifact: eb_deploy.zip
environment-defaults:
  evermarkets:
    branch: null
    repository: null
global:
  application_name: EverMarketsTrading
  default_ec2_keyname: ever-prod
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.2.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
